name: Build Python Application

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


permissions:
  write-all

jobs:
  build:

    runs-on: ubuntu-latest

    # Build exe
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: '3.11' 

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: hunt-match-tracker.spec
    

    # Create release
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
    
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/windows/hunt-match-tracker.exe
        asset_name: hunt-match-tracker-${{ github.ref_name }}.exe
        asset_content_type: application/octet-stream

    