name: Build Python Application

on: 
  push:
    branches: [ 'master' ]


permissions:
  write-all

jobs:
  build:

    runs-on: ubuntu-latest

    # Build exe
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: hunt-match-tracker.spec
    

    # Create release
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.GITHUB_RUN_ID }} | ${{ github.GITHUB_SHA }}
        tag_name: Version_${{ github.GITHUB_RUN_ID }}
    
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/windows/hunt-match-tracker.exe
        asset_name: hunt-match-tracker-${{ github.GITHUB_RUN_ID }}-${{ github.GITHUB_SHA }}.exe
        asset_content_type: application/octet-stream

    