name: Build Python Application

on: 
  push:
    branches: [ 'master' ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List repository
      run: |
        ls $({ github.workspace })