name: Build Python Application

on: 
  push:
    branches: [ 'master' ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: hunt-match-tracker.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Hunt-Match-Tracker.exe
        path: dist/windows